W7D2/bluebird-apr-2020-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #http_method "path", to: "controller#action" write them in this way for custom routes 
  # get "/users", to: "users#index"
  # get "/users/:id", to: "users#show"
  # post "/users", to: "users#create"
  # patch "/users/:id", to: "users#update"
  # delete "/users/:id", to: "users#destroy"

  # resources :users -> this gives all RESTful routes 

  #resources :users, except: [:new, :edit ] #we can filter 
  resources :users do 
    resources :chirps, only: [ :index ] #nesting the chirp index 
  end
  # resources :chirps, only: [:index] #but do we want this?????? (no....)
  resources :chirps, only: [ :show ]

  resource :session, only: [:new, :create, :destroy]
end

W7D2/bluebird-apr-2020-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlueBird20</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1>Twittily Tootily Erik</h1>
    
    <% if logged_in? %>
      <h2>Welcome Back <%= current_user.username %>!!!!!! </h2>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Get out of here">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">Join Us</a>
      <a href="<%= new_session_url %>">Get back in here</a>
    <% end %>
    
    <%= yield %>

    <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
        <h1><%= error %></h1>  
      <% end %>
    <% end %>
    
  </body>
</html>